name: pizzeria-order-processor
services:
#=========================================================================
# SQL Server
# -----------------
# Server: localhost
# Username: sa
# Password: P@ssw0rd1
#=========================================================================
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pizzeria-sql
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd1
      - MSSQL_PID=Evaluation
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - pizzeria-data:/var/opt/mssql

#=========================================================================
# Deploy the database scripts
#=========================================================================
  db-setup:
    image: erikbra/grate:latest
    entrypoint: ['']
    command:
      - /bin/sh
      - -c
      - |
        retry_count=0
        max_retries=5
        while [ $retry_count -lt $max_retries ]
        do
          echo "Attempt $((retry_count + 1))..."
          ./grate --connstring="Server=sql;Database=PizzeriaDB;User Id=sa;Password=P@ssw0rd1;TrustServerCertificate=True" --sqlfilesdirectory=/db --version=1.0.0 --databasetype=sqlserver --silent --outputPath=/output --createdatabase=true --environment=LOCAL --transaction=false
          if [ $? -eq 0 ]; then
            echo "Command succeeded."
            exit 0
          fi
          retry_count=$((retry_count + 1))
          echo "Command failed. Retrying in 5 seconds..."
          sleep 5
        done
        echo "Command failed after $max_retries attempts."
        exit 1
    volumes:
      - ./db:/db
    depends_on:
      - sql

#=========================================================================
# RabbitMQ
# -----------------
# Management UI: http://localhost:15672
# Username: guest
# Password: guest
#=========================================================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pizzeria-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  pizzeria-data:
  rabbitmq-data: